em:
  ip: 10.16.177.65
  user_name: root
  password: aristo1
  version: 8.5.3

ca:
  ip: 10.16.177.66
  user_name: root
  password: aristo1
  version: 8.5.3

radius:
  version:

switch:
  ip:
  os:
  port:
    - gi0/1
    - gi0/2

passthrough:
  ip:
  mac:
