from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Optional
import html


@dataclass
class TestResult:
    test_name: str
    status: str  # "passed", "failed", "skipped", etc.
    details: Optional[str] = None


class HTMLReportGenerator:
    STATUS_COLORS = {
        "passed": "#4CAF50",
        "failed": "#F44336",
        "skipped": "#FFC107",
    }

    def __init__(self, results: List[TestResult], title: str = "Test Report"):
        self.results = results
        self.title = title
        self.generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def generate(self, output_file: str = "report.html"):
        passed = sum(1 for r in self.results if r.status == "passed")
        failed = sum(1 for r in self.results if r.status == "failed")
        skipped = sum(1 for r in self.results if r.status == "skipped")

        total = len(self.results)
        summary_color = (
            "#4CAF50" if failed == 0 else "#F44336"
        )

        rows_html = "\n".join(self._format_row(r) for r in self.results)

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{html.escape(self.title)}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 20px; }}
h1 {{ color: {summary_color}; }}
table {{
  border-collapse: collapse; width: 100%;
  box-shadow: 0 0 10px rgba(0,0,0,0.1);
}}
th, td {{
  text-align: left; padding: 10px; border-bottom: 1px solid #ddd;
}}
tr:hover {{ background-color: #f5f5f5; }}
.status {{
  color: white; padding: 5px 10px; border-radius: 4px; font-weight: bold;
}}
.footer {{
  margin-top: 20px; font-size: 12px; color: #666;
}}
</style>
</head>
<body>

<h1>{html.escape(self.title)}</h1>
<p><strong>Generated:</strong> {self.generated_at}</p>
<p><strong>Summary:</strong> {passed} passed, {failed} failed, {skipped} skipped, total {total}</p>

<table>
<thead>
<tr><th>Test Name</th><th>Status</th><th>Details</th></tr>
</thead>
<tbody>
{rows_html}
</tbody>
</table>

<p class="footer">Generated by Custom Test Framework</p>
</body>
</html>"""

        Path(output_file).write_text(html_content, encoding="utf-8")
        print(f"HTML report generated: {output_file}")

    def _format_row(self, result: TestResult) -> str:
        color = self.STATUS_COLORS.get(result.status, "#9E9E9E")
        details = html.escape(result.details) if result.details else "-"
        return f"""
<tr>
  <td>{html.escape(result.test_name)}</td>
  <td><span class="status" style="background:{color};">{result.status.upper()}</span></td>
  <td>{details}</td>
</tr>
"""


# Example usage:
if __name__ == "__main__":
    results = [
        TestResult("RadiusTestCommanExample", "passed"),
        TestResult("RadiusTestPrametrized[1]", "passed"),
        TestResult("RadiusTestPrametrized[2]", "passed"),
        TestResult("RadiusTestSpecialSetupExample", "passed"),
    ]

    HTMLReportGenerator(results, title="Radius Tests Report").generate("radius_report.html")
